action_entry(Delta)
action_entry(Iseq)
action_entry(Set)
action_entry(Reset)
action_entry(Toggle)
action_entry(List)
action_entry(Load)
action_entry(Unload)
action_entry(InhibitInc)
action_entry(InhibitDec)

