/******************************************************************************
 Auto-generated by trunk/src_plugins/map_plugins.sh - do NOT edit,
 run make map_plugins in trunk/src/ - to change any of the data below,
 edit trunk/src_plugins/PLUGIN/PLUGIN.pup
******************************************************************************/

plugin_header("\nLibrary plugins:\n")
plugin_def("lib_gensexpr",     "#s-expression library",           sdisable, 0, 0)
plugin_def("lib_gtk_common",   "all-hid_gtk common code",         sdisable, 0, 0)
plugin_def("lib_hid_common",   "all-gui-hid common code",         sdisable, 0, 1)
plugin_def("lib_hid_gl",       "openGL rendering",                sdisable, 0, 0)
plugin_def("lib_portynet",     "#IPv4 tcp",                       sbuildin, 1, 0)
plugin_def("lib_wget",         "wget(1) wrapper",                 sdisable, 0, 0)

plugin_header("\nFeature plugins:\n")
plugin_def("irc",              "on-line support (IRC)",           sbuildin, 1, 0)
plugin_def("loghid",           "diagnostics: log HID calls",      sdisable, 1, 0)
plugin_def("stroke",           "mouse gestures",                  sbuildin, 1, 1)
plugin_def("script",           "fungw turing complete scripting", sbuildin, 1, 1)

plugin_header("\nHID plugins:\n")
plugin_def("hid_batch",        "batch process (no-gui HID)",      sbuildin, 1, 1)
plugin_def("hid_gtk2_gdk",     "GTK2 GUI, software render",       sbuildin, 1, 1)
plugin_def("hid_gtk2_gl",      "GTK2 GUI, opengl render",         sbuildin, 1, 1)
plugin_def("hid_lesstif",      "the lesstif gui",                 sbuildin, 1, 1)
plugin_def("hid_remote",       "remote HID server",               sdisable, 0, 0)


plugin_dep("hid_gtk2_gdk", "lib_gtk_common", 01)
plugin_dep("hid_gtk2_gl", "lib_gtk_common", 01)
plugin_dep("hid_gtk2_gl", "lib_hid_gl", 01)
plugin_dep("hid_lesstif", "lib_hid_common", 01)
plugin_dep("irc", "lib_portynet", 0)
plugin_dep("lib_gtk_common", "lib_hid_common", 0)
